apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
  namespace: 5stack
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: 5stack-web
                    operator: In
                    values:
                      - 'true'
      containers:
        - image: ghcr.io/guiiicd/web:latest
          name: web
          ports:
            - containerPort: 3000
          startupProbe:
            httpGet:
              path: /api/healthz
              port: 3000
            periodSeconds: 5
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 2
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 15
            failureThreshold: 3
          env:
            - name: NUXT_PUBLIC_API_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: API_DOMAIN
            - name: NUXT_PUBLIC_WEB_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: WEB_DOMAIN
            - name: NUXT_PUBLIC_DEMOS_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: DEMOS_DOMAIN
            - name: NUXT_PUBLIC_WS_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: WS_DOMAIN
            - name: NUXT_PUBLIC_TYPESENSE_HOST
              valueFrom:
                configMapKeyRef:
                  name: typesense-config
                  key: TYPESENSE_HOST 
            - name: HASURA_GRAPHQL_ADMIN_SECRET
              valueFrom:
                secretKeyRef:
                  name: hasura-secrets
                  key: HASURA_GRAPHQL_ADMIN_SECRET
            - name: TYPESENSE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: typesense-secrets
                  key: TYPESENSE_API_KEY
            - name: STEAM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: steam-secrets
                  key: STEAM_WEB_API_KEY
